name:                hl7parser
version:             0.1.0.0
github:              "stesta/hl7-parser"
license:             MIT
author:              "Steve Testa"
maintainer:          "steve@testasoftware.com"
copyright:           "2022 Testa Software"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hl7parser#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec
- text

library:
  source-dirs: src

tests:
  hl7parser-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hl7parser
    - hspec
    - hspec-megaparsec
    - QuickCheck
    - HUnit
    - hspec-contrib
    - megaparsec 
    - text
